# platform :ios, '8.0'

target 'DevFramework' do
use_frameworks!

pod "AFNetworking"
pod "SDWebImage"
pod "YYModel"
pod "FMDB"
pod "SVProgressHUD"
pod "pop"

  target 'DevFrameworkTests' do
    inherit! :search_paths

  end

  target 'DevFrameworkUITests' do
    inherit! :search_paths

  end

end
